#!/usr/bin/env bash
# changes ip addresses in /etc/hosts file
sed -i 's/^127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/' /etc/hosts
sed -i '/facebook\.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
